### ISSUE TITLE
Beetle species merging wrongly under Plantae

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/xcol#186] opened 2024-10-15 20:05 UTC
The beetle genus Tetralobus (Coleoptera:Elateridae) from this [Plazi dataset](https://www.checklistbank.org/dataset/32037/classification?taxonKey=523387F69F3ECF51FF05FEE4FD28FDE2.taxon) is not merging because there is a [synonym homonym](https://www.checklistbank.org/dataset/304443/nameusage/7NDNQ) in plants (with different author). 
However, the species of that beetle genus are being merged under the accepted genus in plants : [Utricularia](https://www.checklistbank.org/dataset/304443/classification?taxonKey=85JD). 

![image](https://github.com/user-attachments/assets/10a73592-9abb-46ac-a50f-7e9a0f8cf819)

**Comment by DianRHR** [comment] 2024-10-17 03:34
In the log of the [previous release](https://www.checklistbank.org/dataset/303772/about) I found this message: 
![image](https://github.com/user-attachments/assets/e0483902-7b91-4fd1-bd05-c97fcb9c9a7d)

(there is no log file in the [last release](https://www.checklistbank.org/dataset/304443/about)) 

[Tetralobus ](https://www.checklistbank.org/dataset/32037/classification?taxonKey=523387F69F3ECF51FF05FEE4FD28FDE2.taxon)is duplicated in the original source, could that be the reason of the problem?

The rest of the genus under Elateridae in that dataset were [merged ](https://www.checklistbank.org/dataset/304443/names?SECTOR_DATASET_KEY=32037&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&rank=genus&reverse=false&sectorMode=merge&sortBy=taxonomic)properly.

**Comment by mdoering** [comment] 2024-10-17 08:35
That is a bug that should not happen, so yes, that can be a reason for all kinds of bad things.

I don't know why to wasn't moved, but the full log can be found here:
https://download.checklistbank.org/job/50/505c6d31-5b0b-48a2-9a24-86badeb31f19.log.gz

I found it through the job UUID 505c6d31-5b0b-48a2-9a24-86badeb31f19 which is put into the release remarks:
>Created by XRelease#305 505c6d31-5b0b-48a2-9a24-86badeb31f19. Base release 303642.

It also shows the datasetKey of the base release and the release/import attempt 305

**Comment by mdoering** [comment] 2024-10-18 09:28
It might have been due to an older version of Plazi, when the list contained plant taxa!

**Comment by mdoering** [comment] 2024-10-18 09:29
I cannot reproduce the problem with the latest data and code locally. Let's see what the next build brings!

**Comment by mdoering** [comment] 2024-10-22 10:20
fixed in 19th Oct edition:
<img width="1329" alt="image" src="https://github.com/user-attachments/assets/5fe3670c-d36c-41e2-8bd0-4d67c67861b4">

**Closed by mdoering** 2024-10-22 10:20 UTC
Labels: bug
